pipeline {
  agent any

  environment {

    GITHUB_URL = 'https://github.com/EthannyDing/jenkins_demo'
    GIT_CREDENTIALS = '28eacc8f-a3fa-434a-96a3-c9c53f53a213'
  
  }

  parameters {
    booleanParam(name: 'SKIP_TESTING', defaultValue: false)
  }

  stages {

    stage('Start Pipeline'){
        steps {
            echo "Hello Ethan, I'm ready to test your scripts."
        }
    }

    stage('Clone Repo'){
      steps {
        git branch: 'main', [GIT_CREDENTIALS]: , url: [GITHUB_URL]
        sh 'ls'
      }
    }
    
    stage("Prepare Python Environments and Run Tests"){

      agent {
        docker { 
          image 'python:3.10-slim'
        }
      }

      stages {

        stage('Install requirements.txt'){
          steps{
              sh 'ls'
              sh 'pip3 install -r requirements.txt'
          }
        }

        stage('Run tests') {
            when { expression { params.SKIP_TESTING == false } }
            steps {
                sh "pytest tests/test_1.py"
            }
        }

      }
    }
  }
}

